## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
import numpy as np

A = np.random.randint(0, 10, 10)
print(A)
A[(A > 3) & (A < 8)] *= -1
print(A)

[0 3 3 9 9 5 8 9 5 2]
[ 0  3  3  9  9 -5  8  9 -5  2]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
A = np.random.randint(0, 10, 10)
print(A)
A[(A == np.max(A))] = 0
print(A)

[6 2 0 8 6 8 4 5 8 5]
[6 2 0 0 6 0 4 5 0 5]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
A = np.random.randint(0, 10, size=(2,4))
B = np.random.randint(0, 15, size=(5,2))
print(A)
print(B)
C, D = np.meshgrid(A, B, indexing="ij")
result = np.column_stack([C.ravel(), D.ravel()])
print(result)

[[1 9 3 8]
 [1 2 4 8]]
[[ 9  9]
 [12  8]
 [ 5 12]
 [10 10]
 [ 1 10]]
[[ 1  9]
 [ 1  9]
 [ 1 12]
 [ 1  8]
 [ 1  5]
 [ 1 12]
 [ 1 10]
 [ 1 10]
 [ 1  1]
 [ 1 10]
 [ 9  9]
 [ 9  9]
 [ 9 12]
 [ 9  8]
 [ 9  5]
 [ 9 12]
 [ 9 10]
 [ 9 10]
 [ 9  1]
 [ 9 10]
 [ 3  9]
 [ 3  9]
 [ 3 12]
 [ 3  8]
 [ 3  5]
 [ 3 12]
 [ 3 10]
 [ 3 10]
 [ 3  1]
 [ 3 10]
 [ 8  9]
 [ 8  9]
 [ 8 12]
 [ 8  8]
 [ 8  5]
 [ 8 12]
 [ 8 10]
 [ 8 10]
 [ 8  1]
 [ 8 10]
 [ 1  9]
 [ 1  9]
 [ 1 12]
 [ 1  8]
 [ 1  5]
 [ 1 12]
 [ 1 10]
 [ 1 10]
 [ 1  1]
 [ 1 10]
 [ 2  9]
 [ 2  9]
 [ 2 12]
 [ 2  8]
 [ 2  5]
 [ 2 12]
 [ 2 10]
 [ 2 10]
 [ 2  1]
 [ 2 10]
 [ 4  9]
 [ 4  9]
 [ 4 12]
 [ 4  8]
 [ 4  5]
 [ 4 12]
 [ 4 10]
 [ 4 10]
 [ 4  1]
 [ 4 10]
 [ 8  9]
 [ 8  9]
 [ 8 12]
 [ 8  8]
 [ 8  5]
 [ 8 12]
 [ 8 10]
 [ 8 10]
 [ 8  1]
 [ 8 10]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [163]:
A = np.random.randint(0, 5, size=(8,3))
B = np.random.randint(0, 5, size=(2,2))
result = np.zeros(8, dtype=bool)
print(result)
print(A)
print(B)
for index, row1 in enumerate(A):
    counter = 0
    for row2 in B:
        if np.any(np.isin(row1, row2)):
            counter += 1
    if counter == len(B):
        result[index] = True
print(A[result])

[False False False False False False False False]
[[2 0 0]
 [2 4 3]
 [1 2 1]
 [4 1 3]
 [4 4 1]
 [0 2 4]
 [2 2 4]
 [1 2 2]]
[[4 0]
 [0 2]]
[[2 0 0]
 [2 4 3]
 [0 2 4]
 [2 2 4]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [162]:
A = np.random.randint(0, 10, size=(10, 3))
print(A)
print(A[np.max(A, axis=1) != np.min(A, axis=1)])

[[7 4 5]
 [9 5 1]
 [4 7 1]
 [5 4 8]
 [5 1 4]
 [4 1 0]
 [2 4 7]
 [8 7 9]
 [0 5 9]
 [3 1 0]]
[[7 4 5]
 [9 5 1]
 [4 7 1]
 [5 4 8]
 [5 1 4]
 [4 1 0]
 [2 4 7]
 [8 7 9]
 [0 5 9]
 [3 1 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [161]:
A = np.random.randint(0, 3, size=(10, 3))
print(A)
result, index, counter = np.unique(A, axis=0, return_counts=True, return_index=True)
index1 = index[counter == 1]
if len(index1) > 0:
    index_result = np.sort(index1)
    result2 = A[index_result]
    print(result2)

[[1 0 0]
 [0 1 0]
 [2 2 1]
 [1 1 2]
 [0 2 0]
 [0 0 1]
 [2 1 0]
 [1 2 0]
 [1 2 1]
 [2 2 1]]
[[1 0 0]
 [0 1 0]
 [1 1 2]
 [0 2 0]
 [0 0 1]
 [2 1 0]
 [1 2 0]
 [1 2 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [5]:
import math

X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
result = math.prod(X[i][i] for i in range(min(len(X), len(X[0]))) if X[i][i] != 0)
print(result)

X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
result = np.prod(np.diag(X)[np.diag(X) != 0])
print(result)

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [159]:
x = [1, 2, 2, 4] 
y = [4, 2, 1, 2]
result = sorted(x) == sorted(y)
print(result)

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
multiset = np.array_equal(np.sort(x), np.sort(y))
print(multiset)

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [158]:
x = [6, 2, 0, 3, 0, 0, 0, 7, 0]
result = max(x[i] for i in range(1, len(x)) if x[i-1] == 0)
print(result)

x = np.array([6, 2, 0, 3, 0, 0, 0, 7, 0])
result = x[1:][x[:-1] == 0].max()
print(result)

7
7


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [155]:
x = [2, 2, 2, 3, 3, 3, 5]
result = (list(set(x)), [x.count(i) for i in set(x)])
print(result)

x = np.array([2, 2, 2, 3, 3, 3, 5])
result = (np.unique(x, return_counts=True))
print(result)

([2, 3, 5], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1], dtype=int64))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [157]:
from scipy.spatial.distance import cdist

X = [[9, 3],
     [1, 2]]
Y = [[6, 8],
     [6, 3]]
result = cdist(X, Y, metric='euclidean')
print(result)

X = np.array([[9, 3],
              [1, 2]])
Y = np.array([[6, 8],
              [6, 3]])
diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
dist_matrix = np.sqrt(np.sum(diff**2, axis=-1))
print(dist_matrix)

[[5.83095189 3.        ]
 [7.81024968 5.09901951]]
[[5.83095189 3.        ]
 [7.81024968 5.09901951]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [3]:
import numpy as np

calorie_stats = np.loadtxt("cereal.csv", delimiter=",")
print(calorie_stats)

[ 70. 120.  70.  50. 110. 110. 110. 130.  90.  90. 120. 110. 120. 110.
 110. 110. 100. 110. 110. 110. 100. 110. 100. 100. 110. 110. 100. 120.
 120. 110. 100. 110. 100. 110. 120. 120. 110. 110. 110. 140. 110. 100.
 110. 100. 150. 150. 160. 100. 120. 140.  90. 130. 120. 100.  50.  50.
 100. 100. 120. 100.  90. 110. 110.  80.  90.  90. 110. 110.  90. 110.
 140. 100. 110. 110. 100. 100. 110.]


2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [10]:
avarage_calories = calorie_stats/60
print(avarage_calories)

[1.16666667 2.         1.16666667 0.83333333 1.83333333 1.83333333
 1.83333333 2.16666667 1.5        1.5        2.         1.83333333
 2.         1.83333333 1.83333333 1.83333333 1.66666667 1.83333333
 1.83333333 1.83333333 1.66666667 1.83333333 1.66666667 1.66666667
 1.83333333 1.83333333 1.66666667 2.         2.         1.83333333
 1.66666667 1.83333333 1.66666667 1.83333333 2.         2.
 1.83333333 1.83333333 1.83333333 2.33333333 1.83333333 1.66666667
 1.83333333 1.66666667 2.5        2.5        2.66666667 1.66666667
 2.         2.33333333 1.5        2.16666667 2.         1.66666667
 0.83333333 0.83333333 1.66666667 1.66666667 2.         1.66666667
 1.5        1.83333333 1.83333333 1.33333333 1.5        1.5
 1.83333333 1.83333333 1.5        1.83333333 2.33333333 1.66666667
 1.83333333 1.83333333 1.66666667 1.66666667 1.83333333]


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [13]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [15]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [51]:
nth_percentile = np.percentile(calorie_stats, 3.2895)
print(nth_percentile)

60.0004


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [53]:
more_calories = len(calorie_stats[calorie_stats > 60])/len(calorie_stats)
print(more_calories)

0.961038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [54]:
calorie_std = np.std(calorie_stats)
print(calorie_std)
Можно сказать, что наш продукт содержит значительно меньше калорий, нежели большинство аналогов

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
Можно прийти к выводу что наш продукт - топ в индустрии из-за низкого количества колорий и высокого качества!!!!!!